"""Assemble a finished run into a downloadable campaign brief (Markdown)."""
from datetime import datetime

from . import agents


def build_markdown(run: dict) -> str:
    brief = run["brief"]
    outputs = run["outputs"]
    when = datetime.fromtimestamp(run["created_at"]).strftime("%d %B %Y, %H:%M")

    lines = [
        f"# {brief.get('brand', 'Campaign')} — Campaign Brief",
        "",
        f"*Prepared by AEGIS · Ezor Media · {when} · {run['mode']} mode*",
        "",
        "## Brief",
        "",
        f"- **Brand:** {brief.get('brand', '—')}",
        f"- **Product:** {brief.get('product', '—')}",
        f"- **Goal:** {brief.get('goal', '—')}",
        f"- **Audience:** {brief.get('audience', '—')}",
        f"- **Market:** {brief.get('market', '—')}",
        f"- **Budget:** {brief.get('budget', '—')}",
        f"- **Timeline:** {brief.get('timeline', '—')}",
        "",
        "---",
        "",
    ]

    for agent in agents.AGENTS:
        aid = agent["id"]
        lines.append(f"## {agent['icon']} · {agent['name']} — {agent['role']}")
        lines.append("")
        lines.append(outputs.get(aid, "_No output._"))
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*Generated by AEGIS — the campaign intelligence platform for Ezor Media.*")
    return "\n".join(lines)
